### ISSUE TITLE
No changes being logged

### ISSUE THREAD

**Issue by Fox-Robinson** [versionpress/support#44] opened 2016-05-05 18:55 UTC
- VersionPress version: 3
- WordPress version: 4.5

Running on a Siteground shared server. Installation went fine. However, no changes are being registered. The versionpress page remains blank. There is a message at the top which says :

"No route was found matching the URL and request method"

I dont know what that means though.

Can anyone help?

**Comment by borekb** [comment] 2016-05-05 20:14
Changes are probably being recorded fine, just the UI (which is JavaScript-based and depends on REST API on the server) cannot be loaded. @vasek17 any ideas?

**Comment by Fox-Robinson** [comment] 2016-05-06 07:08
![capture](https://cloud.githubusercontent.com/assets/8342674/15066526/ad218874-1361-11e6-86b9-fa3e34428a11.PNG)

Here are the JS errors on the Versionpress page

**Comment by vasek17** [comment] 2016-05-06 07:14
Hello @Fox-Robinson. Can you share your permalink settings?

**Comment by Fox-Robinson** [comment] 2016-05-06 07:35
ENDPOINTS:
"{"name":"Fox Robinson","description":"Wordpress Websites","url":"https:\/\/www.foxrobinson.com\/foxrobinson","home":"https:\/\/www.foxrobinson.com","namespaces":["oembed\/1.0"],"authentication":[],"routes":{"\/":{"namespace":"","methods":["GET"],"endpoints":[{"methods":["GET"],"args":{"context":{"required":false,"default":"view"}}}],"_links":{"self":"https:\/\/www.foxrobinson.com\/wp-json\/"}},"\/oembed\/1.0":{"namespace":"oembed\/1.0","methods":["GET"],"endpoints":[{"methods":["GET"],"args":{"namespace":{"required":false,"default":"oembed\/1.0"},"context":{"required":false,"default":"view"}}}],"_links":{"self":"https:\/\/www.foxrobinson.com\/wp-json\/oembed\/1.0"}},"\/oembed\/1.0\/embed":{"namespace":"oembed\/1.0","methods":["GET"],"endpoints":[{"methods":["GET"],"args":{"url":{"required":true},"format":{"required":false,"default":"json"},"maxwidth":{"required":false,"default":600}}}],"_links":{"self":"https:\/\/www.foxrobinson.com\/wp-json\/oembed\/1.0\/embed"}}},"_links":{"help":[{"href":"http:\/\/v2.wp-api.org\/"}]}}"

"{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}"

Permalinks are set to post name

**Comment by vasek17** [comment] 2016-05-06 07:53
It looks like the VersionPress endpoints have not been registered correctly. Do you have any plugins installed?

**Comment by Fox-Robinson** [comment] 2016-05-06 08:01
Yes I have. Its a live site and I was testing Versionpress on it. There are quite a few pluigns already active.

**Comment by Fox-Robinson** [comment] 2016-05-06 08:06
I have just rolled out a fresh Wordpress site and then installed Versionpress and it is working correctly

**Comment by vasek17** [comment] 2016-05-06 08:12
Are you trying the fresh WP site at the same server/environment as the live site?
If that works, I think it is caused by some incompatible plugin. Maybe you could try the fresh WP site with the same plugins as in the live site.

**Comment by Fox-Robinson** [comment] 2016-05-06 08:13
Yes, its on the same hosting environment (Siteground) . Everything is the same except the live site has SSL on it

**Comment by vasek17** [comment] 2016-05-06 10:09
OK, it really looks some plugin is incompatible. You can try to investigate more which one it is. We're currently working on support for 3rd party plugins for the VersionPress v4.0 (see https://github.com/versionpress/versionpress/issues/1036)

**Comment by Fox-Robinson** [comment] 2016-05-06 10:12
So to clarify, did  plugin cause Versionpress to not install correctly? I turned off all plugins on my live site but Versionpress still did not work.

**Comment by vasek17** [comment] 2016-05-06 10:21
I think it is the cause. Can you please try to reinstall VersionPress with the plugins turned off? Are there any errors displayed during install and activation?

Here is the code that should register the VersionPress REST API routes:
https://github.com/versionpress/versionpress/blob/622a2fca06a71e6e8ad802901b84fa16ed4563be/plugins/versionpress/setup-hooks.php#L960
https://github.com/versionpress/versionpress/blob/622a2fca06a71e6e8ad802901b84fa16ed4563be/plugins/versionpress/src/Api/VersionPressApi.php#L56

**Comment by Fox-Robinson** [comment] 2016-05-09 09:34
Uninstalling Versionpress has given my site a 403 forbidden page and messed up my frontend: https://www.foxrobinson.com/

**Comment by borekb** [comment] 2016-05-09 09:37
We actually had a similar report about SiteGround in this ticket: https://github.com/versionpress/support/issues/46. Could you try to contact their support to find out what is going on? Seems to be specific to SiteGround.

**Comment by Fox-Robinson** [comment] 2016-05-09 09:54
Thanks for the quick reply. Yes indeed the root folder had its permissions reset. Fixed now. Have contacted Siteground to see what they say about the 'why' of it.

**Comment by Fox-Robinson** [comment] 2016-05-09 09:57
I uninstalled versionpress, deactivated all plugins and then re-installed Versionpress. No error messages during install, activation or setup but still not displaying any changes.

https://www.foxrobinson.com/wp-json/versionpress displays:

"{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}"

**Comment by Fox-Robinson** [comment] 2016-05-09 10:01
New error message on Verisonpress page:

"Connection Error: VersionPress is not able to connect to WordPress site. Please try refreshing the page."

**Comment by vasek17** [comment] 2016-05-09 10:48
The error message is displayed because the plugin tries to communicate with REST API endpoints that are not registered correctly. It is quite wierd that the fresh WP site is working properly. 

Could you try to debug if methods [`versionpress_api_init`](https://github.com/versionpress/versionpress/blob/622a2fca06a71e6e8ad802901b84fa16ed4563be/plugins/versionpress/setup-hooks.php#L961) and [`VersionPressApi::registerRoutes`](https://github.com/versionpress/versionpress/blob/622a2fca06a71e6e8ad802901b84fa16ed4563be/plugins/versionpress/src/Api/VersionPressApi.php#L56) are being called? Thank you.

**Comment by Fox-Robinson** [comment] 2016-05-09 18:35
I have reached the limit of what I am willing to test on this particular site. 

Siteground installed Versionpress and confirmed that Versionpress changes the root folder file permission when uninstalled. They said that it was an issue with the pluign and to contact you.

**Comment by borekb** [comment] 2016-05-09 18:50
Thanks @Fox-Robinson, I fully appreciate your situation. We'll try to open an account on SiteGround and try to reproduce the issue on some test site. Closing this issue for now.

**Closed by borekb** 2016-05-09 18:50 UTC

**Comment by pavelevap** [comment] 2016-05-23 19:00
Hi @Fox-Robinson,

I am suspecting HTTPS a little bit in this case, do you use Lets Encrypt or any other specific certificate?

We were also able to find the cause of permission [problem](https://github.com/versionpress/versionpress/issues/945) observed after unistalling VersionPress, it will be fixed in upcoming 3.0.1.

**Comment by Fox-Robinson** [comment] 2016-05-24 16:50
Hi pavelevap,

I am not very familiar with SSL certificates and cannot answer this question. As this was only a test and most sites will not be SSL I am not going to pursue this. Thanks for your interest.
