### ISSUE TITLE
The process "git clone" exceeded the timeout of 60 seconds

### ISSUE THREAD

**Issue by digitalartworks** [versionpress/support#4] opened 2015-11-30 08:28 UTC
When I clone repository, I got error:
PHP Fatal error:  Uncaught exception 'Symfony\Component\Process\Exception\ProcessTimedOutException' with message 'The process "git clone '/var/www/xxx/prod/' '/var/www/xxx/dev'" exceeded the timeout of 60 seconds.' in /var/www/xxx/prod/wp-content/plugins/versionpress/vendor/symfony/process/Symfony/Component/Process/Process.php:1219
Can You suggest me what can I do? I’ve tried to raise composer timeout but it changed nothing.

**Comment by pavelevap** [comment] 2015-11-30 08:46
Hi, I had similar problems during initial commit (after activating VersionPress). It is probably caused by very large repository.

You can try to change default value (60) for `$timeout` in the same file `wp-content/plugins/versionpress/vendor/symfony/process/Symfony/Component/Process/Process.php` on line 141.

**Comment by borekb** [comment] 2015-11-30 08:54
Yes, that should do as a quick workaround. In the next release (possibly in 2.2) we will get rid of this arbitrary 60s timeout in `Symfony\Process` so this problem should be gone.

(Funny thing is that we've already removed this limit earlier this year - in April - for initialization but when we introduced the cloning & merging features, we forgot to raise the timeout there as well. Sorry for that..)

**Comment by borekb** [comment] 2015-11-30 08:54
Will be fixed in VersionPress 2.2.

**Closed by borekb** 2015-11-30 08:54 UTC

**Comment by digitalartworks** [comment] 2015-11-30 08:59
Thanks guys for support! I'll check it.
