### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by ranjithapr** [versionpress/support#91] opened 2017-03-22 09:37 UTC
Please be specific when describing the issue. Also, these details will help:

 wordpress-version' => '4.7.3',
'versionpress-version' => '3.0.2',
'operating-system' => 'Linux andev10wccge100 2.6.32-642.11.1.el6.x86_64 #1 SMP Fri Nov 18 19:25:05 UTC 2016 x86_64',
'php-version' => '7.0.16',
'php-sapi' => 'fpm-fcgi',
'git-version' => '2.1.2',
'git-full-path' => '/usr/bin/git',
i see that vp is activated, however if i edit any page in the wordpress, it is not tracked under change history by VP

**Comment by borekb** [comment] 2017-03-22 09:43
Hi, sorry for the trouble. Can you post a screenshot of the VersionPress screen in wp-admin? Are there any errors in your PHP error log?

**Comment by ranjithapr** [comment] 2017-03-22 10:26
Permission denied in /needful/allsites/1001/wp-content/plugins/versionpress/src/Initialization/WpConfigSplitter.php on line 57
[22-Mar-2017 10:13:13 UTC] PHP Warning:  file_put_contents(/usr/share/nginx/html/1001/wp-config.php): failed to open stream: Permission denied in /needful/allsites/1001/wp-content/plugins/versionpress/src/Utils/WpConfigEditor.php on line 104
[22-Mar-2017 10:13:13 UTC] PHP Fatal error:  Uncaught UnexpectedValueException: FilesystemIterator::__construct(/usr/share/nginx/html/1001/wp-content/vpdb/comments/A8): failed to open dir: Permission denied in /needful/allsites/1001/wp-content/plugins/versionpress/vendor/symfony/filesystem/Symfony/Component/Filesystem/Filesystem.php:159

**Comment by ranjithapr** [comment] 2017-03-22 10:26
What shoule be done to fix this

**Comment by ranjithapr** [comment] 2017-03-22 10:33
Latest Error is below:
 PHP Fatal error:  Uncaught UnexpectedValueException: FilesystemIterator::__construct(/usr/share/nginx/html/1001/wp-content/vpdb/comments/A8): failed to open dir: Permission denied in /needful/allsites/1001/wp-content/plugins/versionpress/vendor/symfony/filesystem/Symfony/Component/Filesystem/Filesystem.php:159
Stack trace:
#0 /needful/allsites/1001/wp-content/plugins/versionpress/vendor/symfony/filesystem/Symfony/Component/Filesystem/Filesystem.php(159): FilesystemIterator->__construct('/usr/share/ngin...')
#1 /needful/allsites/1001/wp-content/plugins/versionpress/vendor/symfony/filesystem/Symfony/Component/Filesystem/Filesystem.php(159): Symfony\Component\Filesystem\Filesystem->remove(Array)
#2 /needful/allsites/1001/wp-content/plugins/versionpress/vendor/symfony/filesystem/Symfony/Component/Filesystem/Filesystem.php(159): Symfony\Component\Filesystem\Filesystem->remove(Array)
#3 /needful/allsites/1001/wp-content/plugins/versionpress/src/Utils/FileSystem.php(49): Symfony\Component\Filesystem\Filesystem->remove(Array)
#4 /need in /needful/allsites/1001/wp-content/plugins/versionpress/vendor/symfony/filesystem/Symfony/Component/Filesystem/Filesystem.php on line 159

**Comment by borekb** [comment] 2017-03-22 11:04
VersionPress needs write permissions to all files & folders of the site. Did you get a warning during the initialization process? Permissions are checked there.

**Comment by ranjithapr** [comment] 2017-03-22 11:13
No warning during initialisation.  
To what user should the permission be given to folders, is it the user which is mentioned in the system info

**Comment by borekb** [comment] 2017-03-22 11:28
The web server user.

**Comment by borekb** [comment] 2017-04-12 13:17
Hi, I'm closing this for now, if you need further help please reopen this issue or create a new one. Thanks.

**Closed by borekb** 2017-04-12 13:17 UTC

**Comment by pavelevap** [comment] 2017-04-12 19:59
Hi @ranjithapr,

I was able to partly [reproduce](https://github.com/versionpress/versionpress/issues/1199) your errors. It is caused by restricted access to `wp-config.php` file.

Do you have any security plugin activated? Do you use any special permissions? Can you check permissions for `wp-config.php` file and `/usr/share/nginx/html/1001/wp-content/vpdb/comments/A8` directory and let us know? VersionPress is checking directory permissions before activation, but this is probably some specific case.
