### ISSUE TITLE
sh: wp: command not found halfway through wp vp clone process

### ISSUE THREAD

**Issue by yingles** [versionpress/support#61] opened 2016-08-30 15:54 UTC
When I'm trying to run wp vp clone --name=staging I'm getting sh: wp: command not found right before the creating the database step. Output looks like this:

Success: Site files cloned
Success: Updated remote configuration
Success: Enabled pushing to the original repository
Success: Enabled pushing to the clone
Success: wp-config.php updated
Success: Copied VersionPress
sh: wp: command not found

I could not find anything to help guide me to the error of my ways. Trying to run on MAMP Pro with php7.0.8

A few things I've tried:

Added /Applications/MAMP/bin/php/php7.0.8/bin to my PATH
Created an alias for 'php /Applications/MAMP/bin/php/php7.0.8/bin/wp-cli.phar'

Running `wp --info` gets me:

PHP binary:    /Applications/MAMP/bin/php/php7.0.8/bin/php
PHP version:    7.0.8
php.ini used:    /Applications/MAMP/bin/php/php7.0.8/conf/php.ini
WP-CLI root dir:    phar://wp-cli.phar
WP-CLI packages dir:    
WP-CLI global config:    
WP-CLI project config:    
WP-CLI version:    0.24.1

Seems odd that it runs wp commands fine until it gets to the point where it should be creating the DB. I am also able to create a DB with the wp-cli `wp db create` commmand as well.

**Comment by borekb** [comment] 2016-08-30 16:58
What it comes down is that the code calls `Symfony\Process->run()`. You can try creating a test PHP script that would just include Symfony\Process package and call the `run()` method with some `wp` command. If this errors out for you, it's the root cause.

Calling the `run()` function: see our [VPCommandUtils::exec()](https://github.com/versionpress/versionpress/blob/3.x/plugins/versionpress/src/Cli/VPCommandUtils.php#L57) method.

**Comment by borekb** [comment] 2016-09-05 20:50
Closing this for now, please reopen if you need further assistance.

**Closed by borekb** 2016-09-05 20:50 UTC

**Comment by srimal4you** [comment] 2017-08-29 14:02
Were you able to find a solution for this?

**Comment by pavelevap** [comment] 2018-04-17 11:53
Only adding note that there is related support issue: #81. And currently you can define absolute path to WP-CLI by using `VP_WP_CLI_BINARY` constant, see details here: https://github.com/versionpress/versionpress/issues/1186
