### ISSUE TITLE
Activation is hanging

### ISSUE THREAD

**Issue by Mrbrianojee** [versionpress/support#50] opened 2016-05-26 19:50 UTC
Please be specific when describing the issue. Also, these details will help:

- VersionPress version:  3.0
- WordPress version: WordPress 4.5.2
- OS, webserver, PHP: 5.6+
- Git version: 1.9

Hi
I'm trying to get versionpress up and running on my WP site using WPLMS and hosted on FastComet. I've uploaded and activated the plugin (activated in the sense that the versionpress panel becomes available in admin) . There is also an activate button on the versionpress plugin panel. When I click on this it hangs showing the following message.
"Briefly unavailable for scheduled maintenance. Check back in a minute."
I can't get it to move beyond that - when I go back to the admin screen (after a couple of hours in one case)
I did notice one error in the system checks which read:
"Access rules can be installed
VersionPress automatically tries to secure certain locations, like wp-content/vpdb. You either don't have a supported web server or rules cannot be enforced."

I know this plugin will be awesome once I get up and running. Can you help?
Thanks
Brian

**Comment by borekb** [comment] 2016-05-31 19:39
Hi Brian, is the site large by any chance? Like, many posts, comments or other database entities? Is it running some complex plugins? VersionPress doesn't work in those situations very well yet.

**Comment by borekb** [comment] 2016-08-09 16:45
Closing. If you still need assistance please reopen.

**Closed by borekb** 2016-08-09 16:45 UTC

**Comment by tannerchung** [comment] 2018-03-29 17:51
@borekb Can you clarify, when the site is hanging like this during activation, is it that it is still activating and you have to wait or did it crash? If it crashed, can you explain what the issue is? If it didn't crash, is there a way to gather debug data for is to submit to you?

**Comment by borekb** [comment] 2018-03-29 17:57
@tannerchung When it crashes, you should be able to tell, e.g., there's some kind of error message shown, typically. But on a large site, it can take hours to initialize and if your PHP limits are large enough, it can work fine.

**Comment by maurocolella** [comment] 2019-08-06 06:47
Dear Versionpress.

I am facing the same issue with WordPress 5.2.2, VersionPress 4.0-beta2

Or *almost* the same issue.

I disabled all plugins, to make sure I started from a clean slate. Ran operations, found myself with the "site in maintenance" warning.

Removed the `.maintenance` file, reactivated all the plugins, and I find myself now with versionpress successfully tracking changes. 

But I lost a lot of configuration items when disabling/re-enabling the plugins, and I will now need to re-run the operation from a new staging environment.

Can you shed some light as to why the `.maintenance` file is not disabled in my case? All the versionpress health checks are successful, and no plugin was enabled except VP when I first ran the activation.

**Comment by k4u5hik** [comment] 2021-07-22 10:23
Just informing that I am running a multisite with ACF Pro Plugin and the activation has hung and I am unable to delete the plugin.
