### ISSUE TITLE
No VP status; Only continuous scrolling gray bars 

### ISSUE THREAD

**Issue by re2me** [versionpress/support#29] opened 2016-04-05 15:53 UTC
![screenshot 119](https://cloud.githubusercontent.com/assets/18016768/14288492/ec874db4-fb24-11e5-9c3b-7377cb28cb39.png)

**Comment by borekb** [comment] 2016-04-05 16:02
Does the console (`F12`) show any errors? Which status code the server returns for API requests?

**Comment by re2me** [comment] 2016-04-05 16:09
Actually yes – attached.  How do I fix?  Must admit I changed the Wordpress domain from localhost to ‘minos’ and it stopped working after that.

**Comment by borekb** [comment] 2016-04-05 16:22
Please attach directly on GitHub, it cannot process images from email. How exactly did you change the domain?

**Comment by re2me** [comment] 2016-04-05 16:32
Wordpress -<General -> Wordpress Address (URL) & Site Address (URL).

Also did a search of my Ubuntu file system looking for any file called 'display-welcome-panel'  as in "http://minos/index.php/vp-json/versionpress/display-welcome-panel".  Could not find.
![screenshot 122](https://cloud.githubusercontent.com/assets/18016768/14289821/7af81eb6-fb2a-11e5-8599-96ba49c53e3f.png)

**Comment by vasek17** [comment] 2016-04-05 16:43
@re2me Can you share your WordPress Permalink settings?

**Comment by re2me** [comment] 2016-04-05 17:39
![screenshot 123](https://cloud.githubusercontent.com/assets/18016768/14291942/c887cf6a-fb33-11e5-9c44-0c5a893405b0.png)

**Comment by pavelevap** [comment] 2016-04-05 19:18
@re2me: Hi, what is your WordPress and VersionPress version?

`display-welcome-panel` is not a physical directory, it is fine that it does not "exist" in this way, but it should work.

Did you try to re-save Permalink settings (without changes)?

Did you try to change URLs back to `localhost`?

**Comment by re2me** [comment] 2016-04-05 21:39
Change URL’s back to localhost to check, it didn’t work.

It was the Permalink setting.  Once I reset it back to Plain, VP worked.  Also worked when I reset the URL’s back to domain name.

Thanks for your help.

**Comment by pavelevap** [comment] 2016-04-06 12:50
I could not reproduce this issue. I installed WP 4.4.2 and VP 2.2, saved permalinks to `/%postname%/`.

I changed Wordpress Address (URL) & Site Address (URL) and also changed related localhost setup. VersionPress worked well after simple URL change.

@re2me: I am not sure what could be wrong, maybe any conflicting plugin? Could you please share your [System Info](http://docs.versionpress.net/en/troubleshooting/system-info-page)? Did you try to change permalinks back to `/%postname%/`?

**Comment by borekb** [comment] 2016-04-06 12:52
@pavelevap: @re2me already resolved the issue, GitHub just poorly formatted the email. Closing.

**Closed by borekb** 2016-04-06 12:52 UTC
