### ISSUE TITLE
Fatal error on activation

### ISSUE THREAD

**Issue by Hiverize** [versionpress/support#127] opened 2018-01-04 21:53 UTC
When trying to activate, I get the following error:
Fatal error: ReflectionProperty::setValue(): Cannot write property [...]wp-content/plugins/versionpress/src/Utils/AbsoluteUrlReplacer.php on line 105

I am using
  'wordpress-version' => '4.9.1',
  'versionpress-version' => '4.0-beta',
  'operating-system' => 'Linux dd26414 3.13.0-137-generic #186-Ubuntu  x86_64',
  'php-version' => '5.6.32-nmm1',
  'php-sapi' => 'fpm-fcgi',
  'git-version' => '1.9.1',
  'git-full-path' => 'unknown',
  'wp-cli-full-path' => 'wp',

+Permissions

array (
  'exec-user' => '',
  'proc_open-user' => '',
  'php-can-write' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'php-can-delete' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'process-can-write' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'php-can-delete-file-created-by-process' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
)

Please help?

**Comment by pavelevap** [comment] 2018-01-05 10:43
Hi @Hiverize,

it is probably caused by some plugin which stores `mysqli` instance into WordPress database.
Could you please share your [details](https://docs.versionpress.net/en/troubleshooting/system-info-page), especially about installed plugins?
I will create official issue for developers to fix it.

**Comment by pavelevap** [comment] 2018-01-29 19:08
I am closing this issue for now, please reopen if you have additional info or need further assistance.

**Closed by pavelevap** 2018-01-29 19:08 UTC

**Comment by JorgeDDW** [comment] 2018-02-12 22:07
I have the same issue, do you have all the information for the ticket? or you still need more data?

**Comment by pavelevap** [comment] 2018-02-13 09:43
Hi @JorgeDDW,

details about your plugins and theme would be helpful (we still do not have any real-world example). There is an official issue which should ignore this problem generally: https://github.com/versionpress/versionpress/issues/1312

**Comment by JorgeDDW** [comment] 2018-02-13 19:13
Here is the list of plugins: http://nimb.ws/R3kU1J
and im using this theme: https://themeforest.net/item/adventure-tours-wordpress-tourtravel-theme/12781942

**Comment by jr-jaguar** [comment] 2018-07-12 09:29
I've the same issue too. I received this error when activated WPML Multilingual CMS plugin. If need more info, I can send it. Maybe do you know how I can fix it?
