### ISSUE TITLE
Restore-site error

### ISSUE THREAD

**Issue by FWeissenb** [versionpress/support#133] opened 2018-01-28 21:47 UTC
Please be specific when describing the issue. Also, these details will help:

- VersionPress version: 4.0.beta
- WordPress version: latest
- OS, webserver, PHP: docker with wordpress image, modified to start with local user rights
- Git version: 

You can get more details from your system info page: <http://docs.versionpress.net/en/troubleshooting/system-info-page>

I try to make a restore from git and get a failure

`docker exec -it drhouse_wordpress_1 wp vp restore-site --siteurl='http://localhost/' --require=wp-content/plugins/versionpress/src/Cli/vp.php`

and get 

```
Success: Database tables created
Success: VersionPress tables created
Success: Git merge driver added

Warning: syntax error, unexpected '=' in Unknown on line 5
 in /var/www/html/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php on line 165

Call Stack:
    0.0002     389736   1. {main}() /bin/wp:0
    0.0209     791944   2. include('phar:///bin/wp/php/boot-phar.php') /bin/wp:4
    0.0211     793144   3. include('phar:///bin/wp/php/wp-cli.php') phar:///bin/wp/php/boot-phar.php:8
    0.0215     796536   4. WP_CLI\bootstrap() phar:///bin/wp/php/wp-cli.php:23
    0.1667    3030608   5. WP_CLI\Bootstrap\LaunchRunner->process() phar:///bin/wp/php/bootstrap.php:75
    0.1667    3030648   6. WP_CLI\Runner->start() phar:///bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php:23
    0.1682    3085816   7. WP_CLI\Runner->do_early_invoke() phar:///bin/wp/php/WP_CLI/Runner.php:974
    0.1682    3085816   8. WP_CLI\Runner->_run_command_and_exit() phar:///bin/wp/php/WP_CLI/Runner.php:67
    0.1682    3085816   9. WP_CLI\Runner->run_command() phar:///bin/wp/php/WP_CLI/Runner.php:343
    0.1695    3132744  10. WP_CLI\Dispatcher\Subcommand->invoke() phar:///bin/wp/php/WP_CLI/Runner.php:336
    0.1695    3133824  11. call_user_func:{phar:///bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:421}() phar:///bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:421
    0.1695    3133824  12. WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}() phar:///bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:421
    0.1696    3134616  13. call_user_func:{phar:///bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:87}() phar:///bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:87
    0.1696    3134616  14. VersionPress\Cli\VPInternalCommand->finishRestore() phar:///bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:87
    2.0015    4886824  15. VersionPress\Synchronizers\SynchronizationProcess->synchronizeAll() /var/www/html/wp-content/plugins/versionpress/src/Cli/vp-internal.php:107
    2.0118    4975648  16. VersionPress\Synchronizers\SynchronizationProcess->runSynchronizationTasks() /var/www/html/wp-content/plugins/versionpress/src/Synchronizers/SynchronizationProcess.php:57
   41.9128    5407648  17. VersionPress\Synchronizers\Synchronizer->synchronize() /var/www/html/wp-content/plugins/versionpress/src/Synchronizers/SynchronizationProcess.php:66
   41.9128    5407648  18. VersionPress\Synchronizers\Synchronizer->maybeInit() /var/www/html/wp-content/plugins/versionpress/src/Synchronizers/Synchronizer.php:137
   41.9128    5407648  19. VersionPress\Synchronizers\Synchronizer->loadEntitiesFromStorage() /var/www/html/wp-content/plugins/versionpress/src/Synchronizers/Synchronizer.php:203
   41.9128    5407648  20. VersionPress\Storages\DirectoryStorage->loadAll() /var/www/html/wp-content/plugins/versionpress/src/Synchronizers/Synchronizer.php:229
   41.9257    5435288  21. VersionPress\Storages\DirectoryStorage->loadAllFromFiles() /var/www/html/wp-content/plugins/versionpress/src/Storages/DirectoryStorage.php:134
   41.9284    5489800  22. array_map() /var/www/html/wp-content/plugins/versionpress/src/Storages/DirectoryStorage.php:177
   41.9720    5541192  23. VersionPress\Storages\DirectoryStorage->deserializeEntity() /var/www/html/wp-content/plugins/versionpress/src/Storages/DirectoryStorage.php:177
   41.9720    5541192  24. VersionPress\Storages\Serialization\IniSerializer::deserialize() /var/www/html/wp-content/plugins/versionpress/src/Storages/Storage.php:145
   41.9722    5544264  25. parse_ini_string() /var/www/html/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php:165


Warning: Invalid argument supplied for foreach() in /var/www/html/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php on line 397

Call Stack:
    0.0002     389736   1. {main}() /bin/wp:0
    0.0209     791944   2. include('phar:///bin/wp/php/boot-phar.php') /bin/wp:4
    0.0211     793144   3. include('phar:///bin/wp/php/wp-cli.php') phar:///bin/wp/php/boot-phar.php:8
    0.0215     796536   4. WP_CLI\bootstrap() phar:///bin/wp/php/wp-cli.php:23
    0.1667    3030608   5. WP_CLI\Bootstrap\LaunchRunner->process() phar:///bin/wp/php/bootstrap.php:75
    0.1667    3030648   6. WP_CLI\Runner->start() phar:///bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php:23
    0.1682    3085816   7. WP_CLI\Runner->do_early_invoke() phar:///bin/wp/php/WP_CLI/Runner.php:974
    0.1682    3085816   8. WP_CLI\Runner->_run_command_and_exit() phar:///bin/wp/php/WP_CLI/Runner.php:67
    0.1682    3085816   9. WP_CLI\Runner->run_command() phar:///bin/wp/php/WP_CLI/Runner.php:343
    0.1695    3132744  10. WP_CLI\Dispatcher\Subcommand->invoke() phar:///bin/wp/php/WP_CLI/Runner.php:336
    0.1695    3133824  11. call_user_func:{phar:///bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:421}() phar:///bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:421
    0.1695    3133824  12. WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}() phar:///bin/wp/php/WP_CLI/Dispatcher/Subcommand.php:421
    0.1696    3134616  13. call_user_func:{phar:///bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:87}() phar:///bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:87
    0.1696    3134616  14. VersionPress\Cli\VPInternalCommand->finishRestore() phar:///bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php:87
    2.0015    4886824  15. VersionPress\Synchronizers\SynchronizationProcess->synchronizeAll() /var/www/html/wp-content/plugins/versionpress/src/Cli/vp-internal.php:107
    2.0118    4975648  16. VersionPress\Synchronizers\SynchronizationProcess->runSynchronizationTasks() /var/www/html/wp-content/plugins/versionpress/src/Synchronizers/SynchronizationProcess.php:57
   41.9128    5407648  17. VersionPress\Synchronizers\Synchronizer->synchronize() /var/www/html/wp-content/plugins/versionpress/src/Synchronizers/SynchronizationProcess.php:66
   41.9128    5407648  18. VersionPress\Synchronizers\Synchronizer->maybeInit() /var/www/html/wp-content/plugins/versionpress/src/Synchronizers/Synchronizer.php:137
   41.9128    5407648  19. VersionPress\Synchronizers\Synchronizer->loadEntitiesFromStorage() /var/www/html/wp-content/plugins/versionpress/src/Synchronizers/Synchronizer.php:203
   41.9128    5407648  20. VersionPress\Storages\DirectoryStorage->loadAll() /var/www/html/wp-content/plugins/versionpress/src/Synchronizers/Synchronizer.php:229
   41.9257    5435288  21. VersionPress\Storages\DirectoryStorage->loadAllFromFiles() /var/www/html/wp-content/plugins/versionpress/src/Storages/DirectoryStorage.php:134
   41.9284    5489800  22. array_map() /var/www/html/wp-content/plugins/versionpress/src/Storages/DirectoryStorage.php:177
   41.9720    5541192  23. VersionPress\Storages\DirectoryStorage->deserializeEntity() /var/www/html/wp-content/plugins/versionpress/src/Storages/DirectoryStorage.php:177
   41.9720    5541192  24. VersionPress\Storages\Serialization\IniSerializer::deserialize() /var/www/html/wp-content/plugins/versionpress/src/Storages/Storage.php:145
   41.9724    5544296  25. VersionPress\Storages\Serialization\IniSerializer::restoreTypesOfValues() /var/www/html/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php:166

Success: Database synchronized
```

Any ideas?

**Comment by pavelevap** [comment] 2018-01-29 17:17
Hi @FWeissenb,

do you have any plugins active on your site? It could be caused by some edge case that we did not notice yet (data from database are saved into `.ini` files and restored from here). Any chance you could share your database dump to investigate this issue?

**Comment by pavelevap** [comment] 2018-04-24 07:38
I am closing this issue for now, please reopen if you have additional info or need further assistance.

**Closed by pavelevap** 2018-04-24 07:38 UTC
