### ISSUE TITLE
Error: wp-config.php file not found

### ISSUE THREAD

**Issue by johnparkerg** [versionpress/support#132] opened 2018-01-24 23:06 UTC
- VersionPress version: 4.0-beta
- WordPress version: 4.9.2
- OS, webserver, PHP: Ubuntu 16.04.3 , Apache 2.4.18, PHP 7.0.22
- Git version: 2.7.4

## Issue:

I'm getting "Error: wp-config.php file not found" when trying to clone a successfully activated versionpress in wordpress.

## Context:

I've tried doing this as a sudo user, as root (as a test, still I'm ashamed to admit) and as www-data where I got the furthest ahead.

As sudo user i got the following errors:

`PHP Warning:  file_put_contents(/var/www/html/wp-content/vpdb/options/rs/rs_tables_created.ini): failed to open stream: Permission denied in /var/www/html/wp-content/plugins/versionpress/src/Storages/DirectoryStorage.php on line 89`
`Warning: file_put_contents(/var/www/html/wp-content/vpdb/options/rs/rs_tables_created.ini): failed to open stream: Permission denied in /var/www/html/wp-content/plugins/versionpress/src/Storages/DirectoryStorage.php on line 89`

As root and as www-data I got the previously stated error "Error: wp-config.php file not found".

I have a series of custom home made plugins that insert javascript into pages, no big deal. I am also using gitium, which is similar to versionpress, and could be causing the problem except I disabled it and nothing improved.

The server is hosted in digitalocean and it is a VPS with only one wordpress install.

## Dump:

`www-data@new-web-wordpress-1gb-nyc3-01:~$ cd html/`
`www-data@new-web-wordpress-1gb-nyc3-01:~/html$ wp vp clone --name=staging`
`Error: The command cannot derive default clone URL. Please specify the --siteurl parameter.`
`www-data@new-web-wordpress-1gb-nyc3-01:~/html$ wp vp clone --name=staging --siteurl=staging.merenguemerengue.com`
`Success: Site files cloned`
`The Git repo of this site already defines remote 'staging', overwrite it? [y/n] y`
`Success: Updated remote configuration`
`Success: Enabled pushing to the original repository`
`Success: Enabled pushing to the clone`
`Success: wp-config.php updated`
`Success: Copied VersionPress`
`Error: wp-config.php file not found`
`Error: Config file does not exist. Please run 'wp core config' first.`
`Error: Config file does not exist. Please run 'wp core config' first.`
`Error: Config file does not exist. Please run 'wp core config' first.`
`Error: Config file does not exist. Please run 'wp core config' first.`
`Error: Config file does not exist. Please run 'wp core config' first.`
`Error: Config file does not exist. Please run 'wp core config' first.`
`Error: Config file does not exist. Please run 'wp core config' first.`
`Error: Config file does not exist. Please run 'wp core config' first.`
`www-data@new-web-wordpress-1gb-nyc3-01:~/html$ `

Thanks
John

**Comment by pavelevap** [comment] 2018-04-24 08:06
Hi @johnparkerg,

sorry for delay. Did you manage to solve your issue? It looks to me that it is some server configuration problem related to permissions. I never encountered similar issue when cloning website. `staging` folder was created in your `html` folder? Maybe it has different permissions?

**Comment by marekka** [comment] 2018-05-06 21:14
Having the same issue on whm cpanel...

**Comment by pavelevap** [comment] 2018-05-07 09:27
Hi @marekka,

did you experience the same error? It looks like some file permission problem which is hard to reproduce :-( Any chance you could send us credentials (SSH, WP) to some testing (clean) site and describe steps to reproduce?

**Comment by pavelevap** [comment] 2018-07-02 09:57
I am closing this issue for now, please reopen if you have additional info or need further assistance.

**Closed by pavelevap** 2018-07-02 09:57 UTC

**Comment by bh-adrienne** [comment] 2018-12-29 12:54
I'm getting this now as well on a Bluehost site with a successful Versionpress install. The output is particularly frustrating, as I'm trying to follow the documentation.

> 
> Success: Site files cloned
> The Git repo of this site already defines remote 'staging', overwrite it? [y/n] y
> Success: Updated remote configuration
> Success: Enabled pushing to the original repository
> Success: Enabled pushing to the clone
> Success: wp-config.php updated
> Success: Copied VersionPress
> Error: wp-config.php file not found
> Error: Config file does not exist. Please run `wp core config` first.
> Error: Config file does not exist. Please run `wp core config` first.
> Error: Config file does not exist. Please run `wp core config` first.
> Error: Config file does not exist. Please run `wp core config` first.
> Error: Config file does not exist. Please run `wp core config` first.
> Error: Config file does not exist. Please run `wp core config` first.
> Error: Config file does not exist. Please run `wp core config` first.
> Error: Config file does not exist. Please run `wp core config` first.
