### ISSUE TITLE
No write permission in system temp directory

### ISSUE THREAD

**Issue by ArneDBKey2info** [versionpress/support#106] opened 2017-08-04 10:46 UTC
- VersionPress version: 4.0-Beta
- WordPress version: 4.8
- OS, webserver, PHP: Mac osX 
- Git version: 2.11.0

**I get the following error; I don't know how to fix this:**
_VersionPress needs write access in the site root, its nested directories and the system temp directory. Please update the permissions._

My best guess is that it has something to do with:
'sys_temp_dir' => **false**,

but I have no clue how to put these on **true**.

Quick summary
```
array (
  'wordpress-version' => '4.7.5',
  'versionpress-version' => '4.0-beta',
  'operating-system' => 'Darwin MacBook-Pro-van-Arne.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64',
  'php-version' => '7.0.21',
  'php-sapi' => 'apache2handler',
  'git-version' => '2.11.0',
  'git-full-path' => '/usr/bin/git
',
  'wp-cli-full-path' => 'wp',
)
```
Git
```
array (
  'git-binary-as-configured' => 'git',
  'git-available' => true,
  'git-version' => '2.11.0',
  'git-binary-as-called-by-vp' => 'git',
  'git-full-path' => '/usr/bin/git
',
  'versionpress-min-required-version' => '1.9',
  'matches-min-required-version' => true,
)
```
Permissions
```
array (
  'exec-user' => 'daemon',
  'proc_open-user' => 'daemon',
  'php-can-write' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => **false**,
  ),
  'php-can-delete' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'process-can-write' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => **false**,
  ),
  'php-can-delete-file-created-by-process' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
)


```

**Comment by pavelevap** [comment] 2017-08-04 10:53
Hi, this is duplicate of #104?

**Comment by ArneDBKey2info** [comment] 2017-08-04 10:55
Yes,

I just wanted to explain my question more properly, because BorkB said: “chmod, Server Fault and sites like that are a great place to get help with this.”, but I’ve tried googling, and I can’t seem to find any answers that help.

Kind Regards,

**Comment by pavelevap** [comment] 2017-08-10 08:18
Sorry, I am not familiar with MacOS environment. But it is not problem with VersionPress, because we are only checking if it is [possible](https://github.com/versionpress/versionpress/blob/4.0-beta/plugins/versionpress/src/Utils/RequirementsChecker.php#L248) to write to your temp directory (with function `sys_get_temp_dir()`) and you have to take care of it. I would suggest to google for keywords "MacOS sys_get_temp_dir" or "MacOS temp permissions", etc. It can be also somehow related to XAMPP installation so you can browse their forum for related keywords.

**Closed by pavelevap** 2017-08-10 08:18 UTC
