### ISSUE TITLE
Error with Formidable Forms plugin on Frontend Post, Page creation

### ISSUE THREAD

**Issue by rankun** [versionpress/support#107] opened 2017-08-10 00:14 UTC
Error with Formidable Forms plugin on frontend Post, Page creation.

Formidable Forms is a form builder plugin

The posts was created, but the Warning screen appears

Warning: array_merge(): Argument #1 is not an array in /public_html/wp-content/plugins/versionpress/src/Database/WpdbMirrorBridge.php on line 205

Fatal error: Uncaught Exception: Empty sections are not supported in /home/73241-56568.cloudwaysapps.com/yqmtatvgef/public_html/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php:73 Stack trace: #0 /public_html/wp-content/plugins/versionpress/src/Storages/Storage.php(156): VersionPress\Storages\Serialization\IniSerializer::serialize(Array) #1 /public_html/wp-content/plugins/versionpress/src/Storages/DirectoryStorage.php(89): VersionPress\Storages\Storage->serializeEntity('57092502C60A48F...', Array) #2 public_html/wp-content/plugins/versionpress/src/Storages/Mirror.php(45): VersionPress\Storages\DirectoryStorage->save(Array) #3 /home/73241-56568.cloudwaysapps.com/yqmtatvgef/public_html/wp-content/plugins/versionpress/src/Database/WpdbMirrorBridge.php(233): VersionPress\Storages\Mirror->save('post', Array) #4 /public_html/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php on line 73

**Comment by pavelevap** [comment] 2017-08-10 08:05
Hi @rankun,

I tried [Formidable Forms](https://wordpress.org/plugins/formidable/) plugin with some simple form, but I could not reproduce this error ([source](https://github.com/versionpress/versionpress/blob/4.0-beta/plugins/versionpress/src/Storages/Serialization/IniSerializer.php#L73)). Could you please export your form (menu Formidable - Export/Import) and attach it to this issue? Maybe there is some special field or settings which leads to this problem.

But I also looked into database and it seems to me that Formidable Forms plugin uses its own tables: `wp_frm_fields`, `wp_frm_forms`, `wp_frm_items` and `wp_frm_item_metas`. In this case you have to add special support to enable tracking them, see our [docs](https://github.com/versionpress/versionpress/blob/master/docs/Plugin-Support.md). There are some examples to help you understand how it works ([WooCommerce](https://github.com/pavelevap/versionpress-for-woocommerce), [Advanced Custom Fields](https://github.com/versionpress/support/issues/102)).

Please let us know if you need further help!

**Comment by pavelevap** [comment] 2018-02-01 08:51
I am closing this issue for now, please reopen if you have additional info or need further assistance.

**Closed by pavelevap** 2018-02-01 08:51 UTC
