### ISSUE TITLE
Images not showing on server from local

### ISSUE THREAD

**Issue by garygoodger88** [versionpress/support#137] opened 2018-03-18 21:11 UTC
Please be specific when describing the issue. Also, these details will help:

- VersionPress version: 4
- WordPress version: 4.9.4
- OS, webserver, PHP: Ubuntu, Nginx, PHP 7.1

I appear to be experiencing an issue with Versionpress where gallery/media images are not transferring to our staging site from local. 

For example, we have a WooCommerce store, if we add a product on local the main product image will transfer, however, any gallery images will not transfer with the product.

The images do transfer to the staging server, with the correct URL. However they are just not assigned to the product, it's as if the product has no additional gallery images.

We are using a theme with a visual composer, shortcodes etc. We also have the issue for example on the homepage, we have shortcode plugins for images and when transferring from local > staging the same thing happens, the images transfer to the server but they are not assigned to the content on the homepage. 

This seems strange, and any advice would be helpful.

Thank you

**Comment by pavelevap** [comment] 2018-03-19 15:14
Hi @garygoodger88,

problem is probably caused by plugins. VersionPress 4.0-beta supports plugins, but you have to add custom definitions to make it work, see for example [definitions](https://github.com/pavelevap/versionpress-for-woocommerce) for WooCommerce (unfinished, but galleries should work). Please see our [docs](https://github.com/versionpress/versionpress/blob/master/docs/Plugin-Support.md) for detailed info.

**Comment by pavelevap** [comment] 2018-04-17 12:10
I am closing this issue for now, please reopen if you have additional info or need further assistance.

**Closed by pavelevap** 2018-04-17 12:10 UTC
