### ISSUE TITLE
Versionpress not working anymore after upgrading to wordpress 4.7.2

### ISSUE THREAD

**Issue by liasomething** [versionpress/support#84] opened 2017-02-01 23:03 UTC
hello, 

this are my details of the site not working anymore. it never lists the commits, it just shows the loading gif.
i am getting this error:
<b>Fatal error</b>:  Call to a member function getDescription() on null in <b>/home/me/mywebsite/wp-content/plugins/versionpress/src/ChangeInfos/TrackedChangeInfo.php</b> on line <b>104</b><br />

![screen shot 2017-02-01 at 23 40 10](https://cloud.githubusercontent.com/assets/183150/22530149/998fab20-e8da-11e6-93c2-71b538c10618.png)

the details of this website are:
 'wordpress-version' => '4.7.2',
  'versionpress-version' => '4.0-alpha1',
  'operating-system' => 'Linux cavalier 3.2.61-grsec-modsign #1 SMP Tue Aug 12 09:58:26 UTC 2014 x86_64',
  'php-version' => '5.6.29',
  'php-sapi' => 'cgi-fcgi',
  'git-version' => '2.7.3',
  'git-full-path' => '/usr/bin/git

i have another site on which versionpress kept on working after upgrading to WP 4.7.2. it has the following details:
'wordpress-version' => '4.7.2',
  'versionpress-version' => '4.0-alpha1',
  'operating-system' => 'Linux lvps87-230-26-78.dedicated.hosteurope.de 3.13.0-042stab120.5 #1 SMP Tue Oct 25 22:31:12 MSK 2016 x86_64',
  'php-version' => '7.1.0',
  'php-sapi' => 'fpm-fcgi',
  'git-version' => '1.9.1',
  'git-full-path' => '/usr/bin/git

the non-working one is hosted on dreamhost, the working one another server.
i can see a difference in the php-version and the php-sapi lines.
but i just checked another sub-domain i have on dreamhost with the same settings, that i installed for testing versionpress and there it continues to work as well.

do you have an idea what this error message could mean ?

thanks in advance

Lia.-

**Comment by borekb** [comment] 2017-02-03 22:45
Hi @liasomething, thanks for the report. Could you try to reproduce the issue on this site when you transfer it to some other environment? `$actionsInfo` is null on [this line](https://github.com/versionpress/versionpress/blob/325cd8335b4083a17d2e489c5b72b018f7f103eb/plugins/versionpress/src/ChangeInfos/TrackedChangeInfo.php#L104), not sure why.

Also, are there any plugins on this site by any chance?

**Comment by borekb** [comment] 2017-02-11 16:18
@liasomething Hi, I'm going to close this issue to clean things up, if you still need assistance feel free to comment or reopen. Thanks.

**Closed by borekb** 2017-02-11 16:18 UTC

**Comment by liasomething** [comment] 2017-02-11 20:30
hello @borekb, sorry for my delay, i will try out later to move the stuff on the not working website to another place. i am just swamped with other work right now... thanks for your help so far!

**Comment by mBread** [comment] 2017-08-11 09:18
I also have this problem, and I can provide some information on how I think it was triggered in my case. Here's a full description:

*Description:*

When loading the VersionPress page in WP admin console, the VersionPress page doesn't load any change info (see the screenshot below) and it writes this error message in the php error_log file on my server: `PHP Fatal error:  Call to a member function getDescription() on null in /home/public_html/wp-content/plugins/versionpress/src/ChangeInfos/TrackedChangeInfo.php on line 108`.

I had some problems when setting up VP which might have triggered this: After installing VP, activating the plug-in and initialising VP, I then tried to merge some changes in from a couple of existing git repos (containing themes). In doing so, I lost some files in my WP install, including the VP plugin files. After re-installing the VP plug-in, it didn't require initialising again, but generated this error.

Although I caused the problems above during VP installation it looks like the code needs to be more defensive about nulls somewhere. Also, please advise on how to recover from this. I haven't tried transferring it to another environment.

*Error message:*

`PHP Fatal error:  Call to a member function getDescription() on null in /home/public_html/wp-content/plugins/versionpress/src/ChangeInfos/TrackedChangeInfo.php on line 108`

*Screenshot:*

![image](https://user-images.githubusercontent.com/90730/29206999-4cf48dac-7e7c-11e7-9b76-3a7426da6be7.png)

*Info about the environment:*
* WP version 4.8.1
* VP version 4.0-beta
* Other plug-ins: The only other active one is WordPress Importer. Hello Dolly and Akismet are also installed, but not active.
* PHP version 5.6.31
* `uname -a` returns: `Linux (hostname omitted) 2.6.32-673.26.1.lve1.4.27.el6.x86_64 #1 SMP Sun May 7 19:22:54 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux`

Thanks!

**Comment by pavelevap** [comment] 2017-08-11 14:21
Hi @mBread,

I noticed similar error when experimenting with VersionPress and it was caused by damaged commit. I would try following steps:

- Deactivate and delete VersionPress (through WordPress administration) - current repo will be moved to `wp-content/vpbackups` folder.
- Install VersionPress 4.0-beta, activate and initialize once again.

There will be new (and clean) Git repo and error should disappear.

You can also try to inspect current repo and search for strange commits (based on your merge operations), maybe there is missing commit message or something else. It would be helpfull if you could find the real cause of this issue.

**Comment by beabri** [comment] 2020-03-25 15:57
Hi,
I'm having the same issue, for me it's not possible to delete and reinstall Versionpress again, it will cause me a lot of risks and work.
In order to understand what commits lead to this error, I inserted a control inside code on the not working function (!empty($this->actionsInfo)):
```
    public function getChangeDescription()
    {   
        if (empty($this->commitMessageSubject) && !empty($this->actionsInfo)) {
            $this->commitMessageSubject = $this->actionsInfo->getDescription($this->getAction(), $this->getId(), $this->getCustomTags());

            // Backward compatibility - displaying update message for old edit actions
            if ($this->commitMessageSubject === null && $this->getAction() === 'edit') {
                $this->commitMessageSubject = $this->actionsInfo->getDescription('update', $this->getId(), $this->getCustomTags());
            }
        }

        return $this->commitMessageSubject;
    }
```
And confronting the commits inside GUI of Versionpress with the one visible on my git repo, I noticed that Versionpress is not able to read some commit messages, without any visible logic.
Anyway, if I click on commit row on Versionpress GUI I can read Versionpress commit message. Is there a way to fix this behaviour without being forced to reinstall the entire plugin? 
Here attached some screenshot explaining.

Here below commits on my git repo:
![image](https://user-images.githubusercontent.com/16668179/77556898-5d354a00-6eb9-11ea-8d33-64e49ae052dd.png)

Here below commits visible on Versionpress GUI:
![image](https://user-images.githubusercontent.com/16668179/77556980-75a56480-6eb9-11ea-8dbc-845e2f323f42.png)

Thank you!
